name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: '*'
        activate-environment: metabolic
        auto-update-conda: false
        python-version: 3.8
        use-only-tar-bz2: true

    - name: Set up conda environment
      run: |
        mamba env update -f environment.yml
        conda list

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build notebooks

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: notebooks/_build/html
